<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-E8ITG7R" failures="1" tests="1" name="Test" time="15.98" errors="0" timestamp="22 Nov 2024 00:08:30 GMT">
  <testcase classname="com.ghate.tests.HomePageTest" name="TestCase1" time="3.705">
    <failure type="java.lang.AssertionError" message="expected [10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [0]
at com.ghate.tests.HomePageTest.TestCase1(HomePageTest.java:41)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.ghate.tests.HomePageTest" name="googleSearch" time="0.0">
    <ignored/>
  </testcase> <!-- googleSearch -->
</testsuite> <!-- Test -->
